"""PR S13 tests: info-disclosure cleanup, draft caps, and webhook aliases."""

from __future__ import annotations

import hashlib
import hmac
import importlib
import io
import json
import os
import base64
import sys
import time
import types
import uuid
import zipfile
from pathlib import Path
from typing import Any, Dict

from fastapi.testclient import TestClient


API_DIR = os.path.join(os.path.dirname(__file__), "..", "apps", "api")
if API_DIR not in sys.path:
    sys.path.insert(0, API_DIR)


_AUTH_HEADER = {"x-floom-secret": "test-secret-s13"}


def _load_api(
    monkeypatch,
    tmp_path,
    *,
    draft_rate_hour: int = 20,
    run_create_rate_minute: int = 10,
):
    workers_dir = tmp_path / "workers"
    workers_dir.mkdir()
    artifacts_dir = tmp_path / "artifacts"
    artifacts_dir.mkdir()
    db_path = tmp_path / "floom.db"

    monkeypatch.setenv("FLOOM_DB", str(db_path))
    monkeypatch.setenv("FLOOM_WORKERS_DIR", str(workers_dir))
    monkeypatch.setenv("FLOOM_ARTIFACTS_DIR", str(artifacts_dir))
    monkeypatch.setenv("FLOOM_SECRET", _AUTH_HEADER["x-floom-secret"])
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
    monkeypatch.setenv("E2B_API_KEY", "e2b-test")
    monkeypatch.setenv("COMPOSIO_API_KEY", "cmp-test")
    monkeypatch.setenv("COMPOSIO_WEBHOOK_SIGNING_KEY", "whsec-test")
    monkeypatch.setenv("WORKERS_FRONTEND_URL", "https://workers.floom.dev")
    monkeypatch.setenv("WORKEROS_DRAFT_RATE_HOUR", str(draft_rate_hour))
    monkeypatch.setenv("WORKEROS_RUN_CREATE_RATE_LIMIT", str(run_create_rate_minute))
    monkeypatch.setenv("WORKEROS_RUN_CREATE_RATE_WINDOW_SECONDS", "60")

    reset_prefixes = ("auth.", "db.")
    reset_exact = {
        "main",
        "auth",
        "db",
        "files",
        "models",
        "worker_registry",
        "run_service",
        "composio_client",
        "runner_utils",
        "scheduler",
    }
    for name in list(sys.modules):
        if name in reset_exact or name.startswith(reset_prefixes):
            sys.modules.pop(name, None)

    # Avoid startup scheduler side-effects in tests.
    sys.modules["scheduler"] = types.SimpleNamespace(
        start_scheduler=lambda: None,
        stop_scheduler=lambda: None,
    )
    main = importlib.import_module("main")
    main.get_auth_provider.cache_clear()
    return main


def _valid_draft_payload(name: str = "s13-draft-worker") -> Dict[str, Any]:
    worker_yml = f"""
schema_version: "0.3"
name: "{name}"
title: "S13 Draft Worker"
description: "Worker generated by tests."
version: "0.1.0"
targets: ["generic"]
exec:
  entry: "SKILL.md"
  runtime: "skill"
  runner: "e2b"
trigger:
  type: "manual"
"""
    return {
        "worker_yml": worker_yml.strip(),
        "skill_md": "You are a test worker.",
        "suggested_name": name,
        "suggested_title": "S13 Draft Worker",
        "requirements": [],
        "required_connections": [],
        "required_secrets": [],
        "inputs": [{"name": "topic", "type": "string", "label": "Topic", "required": True}],
        "outputs": [{"name": "summary", "type": "markdown", "label": "Summary"}],
        "files": [
            {"path": "worker.yml", "content": worker_yml.strip()},
            {"path": "SKILL.md", "content": "You are a test worker."},
        ],
    }


def _worker_yml(
    name: str,
    *,
    mode: str = "pure-script",
    trigger_type: str = "manual",
) -> str:
    entry = "run.py" if mode == "pure-script" else "SKILL.md"
    runtime = "python311" if mode == "pure-script" else "skill"
    if trigger_type == "webhook":
        trigger_block = """
trigger:
  type: "webhook"
  webhook:
    secret: true
""".strip()
    else:
        trigger_block = f"""
trigger:
  type: "{trigger_type}"
""".strip()
    return f"""
schema_version: "0.3"
name: {name}
title: "S13 Worker {name}"
description: "Worker generated by tests."
version: "0.1.0"
targets: ["generic"]
exec:
  entry: "{entry}"
  runtime: "{runtime}"
  runner: "e2b"
  command: "python run.py"
  inputs: []
  outputs: []
{trigger_block}
""".strip()


def _symlink_bundle(name: str) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("worker.yml", _worker_yml(name))
        info = zipfile.ZipInfo("linked")
        info.external_attr = (0o120777 << 16)
        zf.writestr(info, "target")
    return buf.getvalue()


def _signed_headers(body: bytes, signing_key: str) -> Dict[str, str]:
    msg_id = "msg_s13"
    ts = str(int(time.time()))
    payload = f"{msg_id}.{ts}.{body.decode('utf-8')}".encode()
    digest = hmac.new(signing_key.encode(), payload, hashlib.sha256).digest()
    sig = "v1," + base64.b64encode(digest).decode()
    return {
        "webhook-id": msg_id,
        "webhook-timestamp": ts,
        "webhook-signature": sig,
        "Content-Type": "application/json",
    }


def _insert_minimal_worker(main: Any, worker_id: str, *, secrets: list[str] | None = None) -> None:
    now = main.now_iso()
    skill_version_id = f"skill_{worker_id}"
    manifest = {
        "id": worker_id,
        "name": worker_id,
        "description": "audit test worker",
        "version": "0.1.0",
        "runtime": {"type": "python311", "entrypoint": "run.py", "runner": "e2b"},
        "secrets": secrets or [],
        "inputs": [],
        "outputs": [],
        "trigger": {"type": "manual"},
    }
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO skill_versions (id, name, version, manifest_json, bundle_path, created_at)
            VALUES (?, ?, '0.1.0', ?, ?, ?)
            """,
            (skill_version_id, worker_id, json.dumps(manifest), f"workers/{worker_id}", now),
        )
        conn.execute(
            """
            INSERT INTO workers (id, skill_version_id, name, trigger_type, created_at, owner_id)
            VALUES (?, ?, ?, 'manual', ?, 'federico')
            """,
            (worker_id, skill_version_id, worker_id, now),
        )


def _insert_file_input_worker(main: Any, worker_id: str) -> None:
    now = main.now_iso()
    skill_version_id = f"skill_{worker_id}"
    manifest = {
        "id": worker_id,
        "name": worker_id,
        "description": "audit file input worker",
        "runtime": {"type": "python311", "entrypoint": "run.py", "runner": "e2b"},
        "trigger": {"type": "manual"},
        "inputs": [
            {
                "name": "upload",
                "label": "Upload",
                "type": "file",
                "required": True,
                "accepts": ["text/csv"],
                "max_size_mb": 1,
            }
        ],
        "outputs": [],
    }
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO skill_versions (id, name, version, manifest_json, bundle_path, created_at)
            VALUES (?, ?, '0.1.0', ?, ?, ?)
            """,
            (skill_version_id, worker_id, json.dumps(manifest), f"workers/{worker_id}", now),
        )
        conn.execute(
            """
            INSERT INTO workers (id, skill_version_id, name, trigger_type, created_at, owner_id)
            VALUES (?, ?, ?, 'manual', ?, 'federico')
            """,
            (worker_id, skill_version_id, worker_id, now),
        )


def _insert_sensitive_run(main: Any, tmp_path: Path) -> tuple[str, str]:
    worker_id = f"s13-run-worker-{uuid.uuid4().hex[:8]}"
    run_id = f"run_{uuid.uuid4().hex}"
    now = main.now_iso()
    _insert_minimal_worker(main, worker_id)
    artifacts_dir = tmp_path / "artifacts" / run_id
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    transcript_path = artifacts_dir / "transcript.jsonl"
    transcript_path.write_text(
        json.dumps({"type": "system", "content": "private system prompt"}) + "\n",
        encoding="utf-8",
    )
    result_path = artifacts_dir / "result.txt"
    result_path.write_text("public result artifact", encoding="utf-8")
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO runs
                (id, worker_id, status, trigger_source, runner, input_json, output_json, created_at)
            VALUES (?, ?, 'completed', 'manual', 'skill', ?, ?, ?)
            """,
            (
                run_id,
                worker_id,
                json.dumps({"prompt": "private user input"}),
                json.dumps({"summary": "public output"}),
                now,
            ),
        )
        conn.execute(
            """
            INSERT INTO logs (run_id, level, message, timestamp, trace_id)
            VALUES (?, 'info', ?, ?, ?)
            """,
            (
                run_id,
                "trace_a2278662e7ae4e05 mode=agent runner=e2b private log",
                now,
                "trace_a2278662e7ae4e05",
            ),
        )
        conn.execute(
            """
            INSERT INTO artifacts (id, run_id, name, type, path, size_bytes, created_at)
            VALUES (?, ?, 'transcript.jsonl', 'jsonl', ?, ?, ?)
            """,
            ("art_transcript", run_id, str(transcript_path), transcript_path.stat().st_size, now),
        )
        conn.execute(
            """
            INSERT INTO artifacts (id, run_id, name, type, path, size_bytes, created_at)
            VALUES (?, ?, 'result.txt', 'text', ?, ?, ?)
            """,
            ("art_result", run_id, str(result_path), result_path.stat().st_size, now),
        )
    return run_id, "art_transcript"


def test_system_info_is_redacted(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.get("/system/info", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert set(body.keys()) == {"version", "started_at", "python_version", "runner"}
    assert body["runner"] == "e2b"
    assert "workers_dir" not in body
    assert "db_path" not in body
    assert "artifacts_dir" not in body


def test_platform_config_is_redacted(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    # Simulate one missing required var and one set required var.
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
    monkeypatch.delenv("COMPOSIO_API_KEY", raising=False)

    resp = client.get("/system/platform-config", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert set(body.keys()) == {"all_required_set", "missing", "set_count", "required_count"}
    assert "OPENAI_API_KEY" not in body["missing"]  # set names must not be enumerated
    assert "COMPOSIO_API_KEY" in body["missing"]
    assert body["set_count"] < body["required_count"]


def test_upload_rejects_null_byte_filename(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/uploads",
        headers=_AUTH_HEADER,
        files={"file": ("test.txt\x00.jpg", b"data", "image/jpeg")},
    )

    assert resp.status_code == 400, resp.text
    assert resp.json() == {"detail": "filename must not contain control characters"}


def test_upload_returns_owner_scoped_download_url(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    headers = {**_AUTH_HEADER, "x-floom-user": "upload-owner"}

    resp = client.post(
        "/uploads",
        headers=headers,
        files={"file": ("audit.txt", b"upload body", "text/plain")},
    )

    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["url"].startswith(f"/uploads/{body['sha256']}?download_token=")
    assert body["id"] == body["sha256"]

    download = client.get(body["url"], headers=_AUTH_HEADER)
    assert download.status_code == 200, download.text
    assert download.content == b"upload body"

    spoofed = client.get(
        f"/uploads/{body['sha256']}",
        headers={**_AUTH_HEADER, "x-floom-user": "upload-owner"},
    )
    assert spoofed.status_code == 404, spoofed.text

    tampered = client.get(body["url"].replace("download_token=", "download_token=x"), headers=_AUTH_HEADER)
    assert tampered.status_code == 404, tampered.text

    dedup = client.post(
        "/uploads",
        headers={**_AUTH_HEADER, "x-floom-user": "second-owner"},
        files={"file": ("audit.txt", b"upload body", "text/plain")},
    )
    assert dedup.status_code == 200, dedup.text
    dedup_download = client.get(dedup.json()["url"], headers=_AUTH_HEADER)
    assert dedup_download.status_code == 200, dedup_download.text
    assert dedup_download.content == b"upload body"


def test_get_with_body_is_rejected(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.request("GET", "/workers", headers=_AUTH_HEADER, content=b"x")

    assert resp.status_code == 413, resp.text
    assert resp.json() == {"detail": "Request body not allowed"}


def test_run_creation_quota_is_per_worker_not_ip_global(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, run_create_rate_minute=1)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_ids = [f"s13-run-quota-{idx}" for idx in range(2)]
    for worker_id in worker_ids:
        _insert_minimal_worker(main, worker_id)

    statuses = []
    bodies = []
    for idx, worker_id in enumerate([worker_ids[0], worker_ids[1], worker_ids[0]]):
        headers = {**_AUTH_HEADER, "x-forwarded-for": f"203.0.113.{idx + 1}"}
        resp = client.post(
            f"/workers/{worker_id}/runs",
            headers=headers,
            json={"inputs": {}, "trigger_source": "manual"},
        )
        statuses.append(resp.status_code)
        bodies.append(resp.text)

    assert statuses == [200, 200, 429], bodies
    assert "Retry-After" in resp.headers
    assert resp.json() == {"detail": "Run creation rate limit exceeded: 1/60s"}


def test_replay_route_shares_run_creation_quota(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, run_create_rate_minute=1)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_id = "s13-replay-quota-worker"
    _insert_minimal_worker(main, worker_id)

    first = client.post(
        f"/workers/{worker_id}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {}, "trigger_source": "manual"},
    )
    assert first.status_code == 200, first.text
    run_id = first.json()["run_id"]

    replay = client.post(f"/workers/{worker_id}/runs/{run_id}/replay", headers=_AUTH_HEADER)

    assert replay.status_code == 429, replay.text
    assert replay.json() == {"detail": "Run creation rate limit exceeded: 1/60s"}
    assert "Retry-After" in replay.headers


def test_sweep_connections_has_cooldown(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    first = client.post("/system/sweep-connections", headers=_AUTH_HEADER)
    second = client.post("/system/sweep-connections", headers=_AUTH_HEADER)

    assert first.status_code == 200, first.text
    assert first.json() == {"status": "sweep_started"}
    assert second.status_code == 429, second.text
    assert second.json() == {"detail": "Connection sweep already started recently"}
    assert "Retry-After" in second.headers


def _setup_rate_limited_draft_client(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, draft_rate_hour=2)
    client = TestClient(main.app)
    payload = _valid_draft_payload(name="s13-rate-limited")
    monkeypatch.setattr(main, "_call_draft_llm", lambda *args, **kwargs: payload)
    return main, client


def _consume_two_draft_slots(client: TestClient):
    first = client.post("/workers/draft-from-prompt", json={"prompt": "first"}, headers=_AUTH_HEADER)
    assert first.status_code == 200, first.text
    second = client.post("/workers/draft-and-create", json={"prompt": "second"}, headers=_AUTH_HEADER)
    assert second.status_code == 200, second.text


def test_draft_endpoints_share_hourly_cap(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    third = client.post("/workers/draft-from-prompt", json={"prompt": "third"}, headers=_AUTH_HEADER)
    assert third.status_code == 429, third.text
    assert third.json() == {"detail": "Draft rate limit reached: 2/hour. Try again later."}


def test_draft_file_path_shares_hourly_cap(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, draft_rate_hour=1)
    client = TestClient(main.app)

    first = client.post(
        "/workers/draft-and-create",
        json={"files": [{"path": "worker.yml", "content": _worker_yml("s13-file-draft-one")}]},
        headers=_AUTH_HEADER,
    )
    second = client.post(
        "/workers/draft-and-create",
        json={"files": [{"path": "worker.yml", "content": _worker_yml("s13-file-draft-two")}]},
        headers=_AUTH_HEADER,
    )

    assert first.status_code == 200, first.text
    assert second.status_code == 429, second.text
    assert second.json() == {"detail": "Draft rate limit reached: 1/hour. Try again later."}


def test_draft_limit_sets_retry_after_header(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    third = client.post("/workers/draft-from-prompt", json={"prompt": "third"}, headers=_AUTH_HEADER)
    assert third.status_code == 429, third.text
    assert "Retry-After" in third.headers
    retry_after = int(third.headers["Retry-After"])
    assert 1 <= retry_after <= 3600


def test_system_metrics_includes_drafts_last_hour(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    metrics = client.get("/system/metrics", headers=_AUTH_HEADER)
    assert metrics.status_code == 200, metrics.text
    assert "drafts_last_hour" in metrics.json()
    assert metrics.json()["drafts_last_hour"] == 2


def test_secret_test_blocks_platform_secret_enumeration(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    for name in [
        "OPENAI_API_KEY",
        "FLOOM_SECRET",
        "E2B_API_KEY",
        "COMPOSIO_API_KEY",
        "THIS_SECRET_DOES_NOT_EXIST_AUDIT",
    ]:
        resp = client.post(f"/secrets/{name}/test", headers=_AUTH_HEADER)
        assert resp.status_code == 404, resp.text
        body = resp.text
        assert "valid" not in body
        assert "chars" not in body
        assert "OpenAI" not in body
        assert "not set" not in body
        assert name not in body


def test_secret_test_for_user_secret_is_generic(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    save = client.post(
        "/secrets/USER_AUDIT_SECRET",
        headers=_AUTH_HEADER,
        json={"value": "super-secret-value"},
    )
    assert save.status_code == 200, save.text

    resp = client.post("/secrets/USER_AUDIT_SECRET/test", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    assert resp.json() == {"status": "valid", "reason": "Secret is configured."}
    assert "super-secret-value" not in resp.text
    assert "chars" not in resp.text
    assert "USER_AUDIT_SECRET" not in resp.text


def test_run_download_omits_sensitive_inputs_logs_and_transcript(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, _transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    resp = client.get(f"/runs/{run_id}/download", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    assert resp.headers.get("content-type", "").startswith("application/zip")

    zip_path = tmp_path / "s13-run-download.zip"
    zip_path.write_bytes(resp.content)
    with zipfile.ZipFile(zip_path, "r") as zf:
        names = set(zf.namelist())
        assert "metadata.json" in names
        assert "outputs.json" in names
        assert "README.txt" in names
        assert "artifacts/result.txt" in names
        assert "inputs.json" not in names
        assert "logs.txt" not in names
        assert "artifacts/transcript.jsonl" not in names
        assert "private user input" not in zf.read("outputs.json").decode("utf-8")


def test_run_detail_omits_sensitive_inputs_logs_trace_and_transcript(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    resp = client.get(f"/runs/{run_id}", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["input"] == {}
    assert body["output"] == {"summary": "public output"}
    assert body["transcript"] == []
    assert [artifact["name"] for artifact in body["artifacts"]] == ["result.txt"]
    assert "trace_id" not in resp.text
    assert "trace_a2278662e7ae4e05" not in resp.text
    assert "mode=agent" not in resp.text
    assert "runner=e2b" not in resp.text

    transcript_download = client.get(
        f"/runs/{run_id}/artifacts/{transcript_artifact_id}/download",
        headers=_AUTH_HEADER,
    )
    assert transcript_download.status_code == 404, transcript_download.text


def test_cancel_completed_run_does_not_reveal_existence(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, _transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    existing = client.post(f"/runs/{run_id}/cancel", headers=_AUTH_HEADER)
    missing = client.post("/runs/run_missing_cancel_probe/cancel", headers=_AUTH_HEADER)

    assert existing.status_code == 404, existing.text
    assert missing.status_code == 404, missing.text
    assert existing.json() == missing.json() == {"detail": "Run not found"}
    assert "completed" not in existing.text
    assert run_id not in existing.text


def test_bundle_snapshot_missing_does_not_reveal_run_existence(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, _transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    existing = client.get(f"/runs/{run_id}/bundle/worker.yml", headers=_AUTH_HEADER)
    missing = client.get("/runs/run_missing_bundle_probe/bundle/worker.yml", headers=_AUTH_HEADER)

    assert existing.status_code == 404, existing.text
    assert missing.status_code == 404, missing.text
    assert existing.json() == missing.json() == {"detail": "Bundle file not found"}
    assert run_id not in existing.text


def test_file_input_rejects_foreign_upload_sha(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    worker_id = "s13-file-owner-worker"
    _insert_file_input_worker(main, worker_id)

    content = b"name,score\nAda,98\n"
    sha256 = hashlib.sha256(content).hexdigest()
    main.ensure_blob_dir(sha256).write_bytes(content)
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO files (id, filename, media_type, size_bytes, uploaded_by, uploaded_at, ref_count)
            VALUES (?, 'scores.csv', 'text/csv', ?, 'other-user', ?, 0)
            """,
            (sha256, len(content), main.now_iso()),
        )

    resp = client.post(
        f"/workers/{worker_id}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {"upload": sha256}, "trigger_source": "manual"},
    )

    assert resp.status_code == 403, resp.text
    assert resp.json() == {"detail": "Uploaded file not found: upload"}


def test_stock_worker_delete_is_blocked_even_when_source_missing(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    _insert_minimal_worker(main, "research_brief")

    resp = client.delete("/workers/research_brief", headers=_AUTH_HEADER)
    assert resp.status_code == 403, resp.text
    with main.get_db() as conn:
        row = conn.execute("SELECT id FROM workers WHERE id = 'research_brief'").fetchone()
    assert row is not None


def test_stock_worker_webhook_secret_rotate_is_blocked(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post("/workers/research_brief/webhook-secret/rotate", headers=_AUTH_HEADER)

    assert resp.status_code == 403, resp.text
    assert resp.json() == {"detail": "Stock workers cannot be modified through the API"}


def test_stock_worker_mutation_routes_are_blocked(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    _insert_minimal_worker(main, "research_brief")
    worker_yml = _worker_yml("research_brief")

    create_resp = client.post(
        "/workers",
        headers=_AUTH_HEADER,
        json={"worker_yml": worker_yml, "run_py": "print('pwned')\n"},
    )
    put_resp = client.put(
        "/workers/research_brief",
        headers=_AUTH_HEADER,
        json={"worker_yml": worker_yml, "run_py": "print('pwned')\n"},
    )
    patch_resp = client.patch(
        "/workers/research_brief",
        headers=_AUTH_HEADER,
        json={"input_values": {"topic": "pwned"}},
    )
    files_resp = client.put(
        "/workers/research_brief/files",
        headers=_AUTH_HEADER,
        json={"files": [{"path": "worker.yml", "content": worker_yml}]},
    )

    assert create_resp.status_code == 403, create_resp.text
    assert put_resp.status_code == 403, put_resp.text
    assert patch_resp.status_code == 403, patch_resp.text
    assert files_resp.status_code == 403, files_resp.text


def test_worker_schema_validation_does_not_leak_pydantic_details(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/workers",
        headers=_AUTH_HEADER,
        json={"worker_yml": "name: bad\ndescription: bad\n", "run_py": "print('ok')\n"},
    )

    assert resp.status_code == 400, resp.text
    assert "errors.pydantic.dev" not in resp.text


def test_openapi_does_not_document_webhook_token_auth(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.get("/openapi.json", headers=_AUTH_HEADER)

    assert resp.status_code == 200, resp.text
    assert "?token=<webhook_token>" not in resp.text
    assert "X-Floom-Signature header" not in resp.text


def test_from_bundle_rejects_symlinks(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    name = "s13-symlink-worker"

    resp = client.post(
        "/workers/from-bundle",
        headers=_AUTH_HEADER,
        files={"bundle": ("symlink.zip", io.BytesIO(_symlink_bundle(name)), "application/zip")},
    )

    assert resp.status_code == 400, resp.text
    assert "symlink" in resp.text.lower()
    assert not (tmp_path / "workers" / name).exists()


def test_from_bundle_is_rate_limited(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    responses = [
        client.post(
            "/workers/from-bundle",
            headers=_AUTH_HEADER,
            files={"bundle": ("bad.zip", io.BytesIO(b"not a zip"), "application/zip")},
        )
        for _ in range(11)
    ]

    assert [resp.status_code for resp in responses[:10]] == [400] * 10
    assert responses[10].status_code == 429


def test_webhook_aliases_match_original_routes(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    bad_sig_headers = {
        "webhook-id": "msg_bad",
        "webhook-timestamp": str(int(time.time())),
        "webhook-signature": "v1,bad",
        "Content-Type": "application/json",
    }
    body = json.dumps({"metadata": {"trigger_id": "ct_missing"}}).encode()

    original = client.post("/composio-events", content=body, headers=bad_sig_headers)
    alias = client.post("/webhooks/composio-events", content=body, headers=bad_sig_headers)
    assert original.status_code == 401, original.text
    assert alias.status_code == 401, alias.text
    assert original.json() == alias.json()

    # Valid signatures should behave the same too (404 in both paths with no worker match).
    sig_headers = _signed_headers(body, "whsec-test")
    original_valid = client.post("/composio-events", content=body, headers=sig_headers)
    alias_valid = client.post("/webhooks/composio-events", content=body, headers=sig_headers)
    assert original_valid.status_code == 404, original_valid.text
    assert alias_valid.status_code == 404, alias_valid.text
    assert original_valid.json() == alias_valid.json()

    callback_qs = "?connection_id=unknown_conn&status=success"
    cb_original = client.get(f"/connections/callback{callback_qs}", follow_redirects=False)
    cb_alias = client.get(f"/webhooks/oauth-callback{callback_qs}", follow_redirects=False)
    assert cb_original.status_code == cb_alias.status_code
    assert cb_original.headers.get("location") == cb_alias.headers.get("location")
