"""PR S13 tests: info-disclosure cleanup, draft caps, and webhook aliases."""

from __future__ import annotations

import hashlib
import hmac
import importlib
import io
import json
import os
import base64
import sys
import threading
import time
import types
import uuid
import zipfile
from pathlib import Path
from typing import Any, Dict

from fastapi.testclient import TestClient


API_DIR = os.path.join(os.path.dirname(__file__), "..", "apps", "api")
if API_DIR not in sys.path:
    sys.path.insert(0, API_DIR)


_AUTH_HEADER = {"x-floom-secret": "test-secret-s13"}


def _load_api(
    monkeypatch,
    tmp_path,
    *,
    draft_rate_hour: int = 20,
    run_create_rate_minute: int | None = 10,
):
    workers_dir = tmp_path / "workers"
    workers_dir.mkdir()
    artifacts_dir = tmp_path / "artifacts"
    artifacts_dir.mkdir()
    contexts_dir = tmp_path / "contexts"
    contexts_dir.mkdir()
    db_path = tmp_path / "floom.db"

    monkeypatch.setenv("FLOOM_DB", str(db_path))
    monkeypatch.setenv("FLOOM_WORKERS_DIR", str(workers_dir))
    monkeypatch.setenv("FLOOM_ARTIFACTS_DIR", str(artifacts_dir))
    monkeypatch.setenv("FLOOM_CONTEXTS_DIR", str(contexts_dir))
    monkeypatch.setenv("FLOOM_SECRET", _AUTH_HEADER["x-floom-secret"])
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
    monkeypatch.setenv("E2B_API_KEY", "e2b-test")
    monkeypatch.setenv("COMPOSIO_API_KEY", "cmp-test")
    monkeypatch.setenv("COMPOSIO_WEBHOOK_SIGNING_KEY", "whsec-test")
    monkeypatch.setenv("WORKERS_FRONTEND_URL", "https://localhost:3000")
    monkeypatch.setenv("WORKEROS_DRAFT_RATE_HOUR", str(draft_rate_hour))
    if run_create_rate_minute is None:
        monkeypatch.delenv("WORKEROS_RUN_CREATE_RATE_LIMIT", raising=False)
    else:
        monkeypatch.setenv("WORKEROS_RUN_CREATE_RATE_LIMIT", str(run_create_rate_minute))
    monkeypatch.setenv("WORKEROS_RUN_CREATE_RATE_WINDOW_SECONDS", "60")

    reset_prefixes = ("auth.", "db.", "routers")
    reset_exact = {
        "main",
        "auth",
        "contexts",
        "db",
        "files",
        "models",
        "worker_registry",
        "run_service",
        "composio_client",
        "runner_utils",
        "scheduler",
    }
    for name in list(sys.modules):
        if name in reset_exact or name.startswith(reset_prefixes):
            sys.modules.pop(name, None)

    # Avoid startup scheduler side-effects in tests.
    sys.modules["scheduler"] = types.SimpleNamespace(
        start_scheduler=lambda: None,
        stop_scheduler=lambda: None,
    )
    main = importlib.import_module("main")
    run_service = importlib.import_module("run_service")
    run_service.register_sse_publisher(main._sse_publish)
    run_service.register_part_publisher(main._run_part_publish)
    main.get_auth_provider.cache_clear()
    return main


def _valid_draft_payload(name: str = "s13-draft-worker") -> Dict[str, Any]:
    worker_yml = f"""
schema_version: "0.3"
name: "{name}"
title: "S13 Draft Worker"
description: "Worker generated by tests."
version: "0.1.0"
targets: ["generic"]
exec:
  entry: "SKILL.md"
  runtime: "skill"
  runner: "e2b"
trigger:
  type: "manual"
"""
    return {
        "worker_yml": worker_yml.strip(),
        "skill_md": "You are a test worker.",
        "suggested_name": name,
        "suggested_title": "S13 Draft Worker",
        "requirements": [],
        "required_connections": [],
        "required_secrets": [],
        "inputs": [{"name": "topic", "type": "string", "label": "Topic", "required": True}],
        "outputs": [{"name": "summary", "type": "markdown", "label": "Summary"}],
        "files": [
            {"path": "worker.yml", "content": worker_yml.strip()},
            {"path": "SKILL.md", "content": "You are a test worker."},
        ],
    }


def _worker_yml(
    name: str,
    *,
    mode: str = "pure-script",
    trigger_type: str = "manual",
) -> str:
    entry = "run.py" if mode == "pure-script" else "SKILL.md"
    runtime = "python311" if mode == "pure-script" else "skill"
    if trigger_type == "webhook":
        trigger_block = """
trigger:
  type: "webhook"
  webhook:
    secret: true
""".strip()
    else:
        trigger_block = f"""
trigger:
  type: "{trigger_type}"
""".strip()
    return f"""
schema_version: "0.3"
name: {name}
title: "S13 Worker {name}"
description: "Worker generated by tests."
version: "0.1.0"
targets: ["generic"]
exec:
  entry: "{entry}"
  runtime: "{runtime}"
  runner: "e2b"
  command: "python run.py"
  inputs: []
  outputs: []
{trigger_block}
""".strip()


def _symlink_bundle(name: str) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("worker.yml", _worker_yml(name))
        info = zipfile.ZipInfo("linked")
        info.external_attr = (0o120777 << 16)
        zf.writestr(info, "target")
    return buf.getvalue()


def _nested_traversal_bundle(name: str) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("worker.yml", _worker_yml(name))
        zf.writestr("nested/../../../../etc/passwd", "x")
    return buf.getvalue()


def _signed_headers(body: bytes, signing_key: str) -> Dict[str, str]:
    msg_id = "msg_s13"
    ts = str(int(time.time()))
    payload = f"{msg_id}.{ts}.{body.decode('utf-8')}".encode()
    digest = hmac.new(signing_key.encode(), payload, hashlib.sha256).digest()
    sig = "v1," + base64.b64encode(digest).decode()
    return {
        "webhook-id": msg_id,
        "webhook-timestamp": ts,
        "webhook-signature": sig,
        "Content-Type": "application/json",
    }


def _insert_minimal_worker(
    main: Any,
    worker_id: str,
    *,
    secrets: list[str] | None = None,
    owner_id: str = "local-user",
) -> None:
    now = main.now_iso()
    skill_version_id = f"skill_{worker_id}"
    manifest = {
        "id": worker_id,
        "name": worker_id,
        "description": "audit test worker",
        "version": "0.1.0",
        "runtime": {"type": "python311", "entrypoint": "run.py", "runner": "e2b"},
        "secrets": secrets or [],
        "inputs": [],
        "outputs": [],
        "trigger": {"type": "manual"},
    }
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO skill_versions (id, name, version, manifest_json, bundle_path, created_at)
            VALUES (?, ?, '0.1.0', ?, ?, ?)
            """,
            (skill_version_id, worker_id, json.dumps(manifest), f"workers/{worker_id}", now),
        )
        conn.execute(
            """
            INSERT INTO workers (id, skill_version_id, name, trigger_type, created_at, owner_id)
            VALUES (?, ?, ?, 'manual', ?, ?)
            """,
            (worker_id, skill_version_id, worker_id, now, owner_id),
        )


def _insert_file_input_worker(main: Any, worker_id: str, *, owner_id: str = "local-user") -> None:
    now = main.now_iso()
    skill_version_id = f"skill_{worker_id}"
    manifest = {
        "id": worker_id,
        "name": worker_id,
        "description": "audit file input worker",
        "runtime": {"type": "python311", "entrypoint": "run.py", "runner": "e2b"},
        "trigger": {"type": "manual"},
        "inputs": [
            {
                "name": "upload",
                "label": "Upload",
                "type": "file",
                "required": True,
                "accepts": ["text/csv"],
                "max_size_mb": 1,
            }
        ],
        "outputs": [],
    }
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO skill_versions (id, name, version, manifest_json, bundle_path, created_at)
            VALUES (?, ?, '0.1.0', ?, ?, ?)
            """,
            (skill_version_id, worker_id, json.dumps(manifest), f"workers/{worker_id}", now),
        )
        conn.execute(
            """
            INSERT INTO workers (id, skill_version_id, name, trigger_type, created_at, owner_id)
            VALUES (?, ?, ?, 'manual', ?, ?)
            """,
            (worker_id, skill_version_id, worker_id, now, owner_id),
        )


def _insert_sensitive_run(main: Any, tmp_path: Path) -> tuple[str, str]:
    worker_id = f"s13-run-worker-{uuid.uuid4().hex[:8]}"
    run_id = f"run_{uuid.uuid4().hex}"
    now = main.now_iso()
    _insert_minimal_worker(main, worker_id)
    artifacts_dir = tmp_path / "artifacts" / run_id
    artifacts_dir.mkdir(parents=True, exist_ok=True)
    transcript_path = artifacts_dir / "transcript.jsonl"
    transcript_path.write_text(
        json.dumps({"type": "system", "content": "private system prompt"}) + "\n",
        encoding="utf-8",
    )
    result_path = artifacts_dir / "result.txt"
    result_path.write_text("public result artifact", encoding="utf-8")
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO runs
                (id, worker_id, status, trigger_source, runner, input_json, output_json, created_at)
            VALUES (?, ?, 'completed', 'manual', 'skill', ?, ?, ?)
            """,
            (
                run_id,
                worker_id,
                json.dumps({"prompt": "private user input"}),
                json.dumps({"summary": "public output"}),
                now,
            ),
        )
        conn.execute(
            """
            INSERT INTO logs (run_id, level, message, timestamp, trace_id)
            VALUES (?, 'info', ?, ?, ?)
            """,
            (
                run_id,
                "trace_a2278662e7ae4e05 mode=agent runner=e2b private log",
                now,
                "trace_a2278662e7ae4e05",
            ),
        )
        conn.execute(
            """
            INSERT INTO artifacts (id, run_id, name, type, path, size_bytes, created_at)
            VALUES (?, ?, 'transcript.jsonl', 'jsonl', ?, ?, ?)
            """,
            ("art_transcript", run_id, str(transcript_path), transcript_path.stat().st_size, now),
        )
        conn.execute(
            """
            INSERT INTO artifacts (id, run_id, name, type, path, size_bytes, created_at)
            VALUES (?, ?, 'result.txt', 'text', ?, ?, ?)
            """,
            ("art_result", run_id, str(result_path), result_path.stat().st_size, now),
        )
    return run_id, "art_transcript"


def test_system_info_is_redacted(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.get("/system/info", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert set(body.keys()) == {"version", "started_at", "python_version", "runner"}
    assert body["runner"] == "e2b"
    assert "workers_dir" not in body
    assert "db_path" not in body
    assert "artifacts_dir" not in body


def test_platform_config_is_redacted(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    # Simulate one missing required var and one set required var.
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
    monkeypatch.delenv("COMPOSIO_API_KEY", raising=False)

    resp = client.get("/system/platform-config", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert set(body.keys()) == {"all_required_set", "missing", "set_count", "required_count"}
    assert "OPENAI_API_KEY" not in body["missing"]  # set names must not be enumerated
    assert "COMPOSIO_API_KEY" in body["missing"]
    assert body["set_count"] < body["required_count"]


def test_upload_rejects_null_byte_filename(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/uploads",
        headers=_AUTH_HEADER,
        files={"file": ("test.txt\x00.jpg", b"data", "image/jpeg")},
    )

    assert resp.status_code == 400, resp.text
    assert resp.json() == {"detail": "filename must not contain control characters"}


def test_upload_rejects_blocked_inner_extension(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/uploads",
        headers=_AUTH_HEADER,
        files={"file": ("shell.php.jpg", b"<?php echo 1; ?>", "image/jpeg")},
    )

    assert resp.status_code == 400, resp.text
    assert resp.json() == {"detail": "Upload filename contains blocked inner extension '.php'"}


def test_upload_requires_auth(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/uploads",
        files={"file": ("audit.txt", b"upload body", "text/plain")},
    )

    assert resp.status_code == 401, resp.text


def test_upload_rejects_path_traversal_filename(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/uploads",
        headers=_AUTH_HEADER,
        files={"file": ("../../etc/passwd.txt", b"upload body", "text/plain")},
    )

    assert resp.status_code == 400, resp.text
    assert resp.json() == {
        "detail": "filename must not contain path separators, leading dots, or '..' segments"
    }


def test_upload_returns_owner_scoped_download_url(monkeypatch, tmp_path):
    monkeypatch.setenv("WORKEROS_ENABLE_USER_HEADER_SCOPE", "1")
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    headers = {**_AUTH_HEADER, "x-floom-user": "upload-owner"}

    resp = client.post(
        "/uploads",
        headers=headers,
        files={"file": ("audit.txt", b"upload body", "text/plain")},
    )

    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["url"].startswith(f"/uploads/{body['sha256']}?download_token=")
    assert body["id"] == body["sha256"]

    download = client.get(body["url"], headers=headers)
    assert download.status_code == 200, download.text
    assert download.content == b"upload body"

    foreign = client.get(body["url"], headers={**_AUTH_HEADER, "x-floom-user": "foreign-user"})
    assert foreign.status_code == 404, foreign.text

    spoofed = client.get(
        f"/uploads/{body['sha256']}",
        headers=headers,
    )
    assert spoofed.status_code == 404, spoofed.text

    tampered = client.get(body["url"].replace("download_token=", "download_token=x"), headers=headers)
    assert tampered.status_code == 404, tampered.text

    dedup_headers = {**_AUTH_HEADER, "x-floom-user": "second-owner"}
    dedup = client.post(
        "/uploads",
        headers=dedup_headers,
        files={"file": ("audit.txt", b"upload body", "text/plain")},
    )
    assert dedup.status_code == 200, dedup.text
    dedup_download = client.get(dedup.json()["url"], headers=dedup_headers)
    assert dedup_download.status_code == 200, dedup_download.text
    assert dedup_download.content == b"upload body"


def test_file_input_accepts_dedup_upload_for_second_owner(monkeypatch, tmp_path):
    monkeypatch.setenv("WORKEROS_ENABLE_USER_HEADER_SCOPE", "1")
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_id = "s13-file-dedup-worker"
    _insert_file_input_worker(main, worker_id, owner_id="upload-owner-b")

    owner_a = {**_AUTH_HEADER, "x-floom-user": "upload-owner-a"}
    owner_b = {**_AUTH_HEADER, "x-floom-user": "upload-owner-b"}
    first = client.post(
        "/uploads",
        headers=owner_a,
        files={"file": ("scores.csv", b"name,score\nAda,98\n", "text/csv")},
    )
    assert first.status_code == 200, first.text

    second = client.post(
        "/uploads",
        headers=owner_b,
        files={"file": ("scores.csv", b"name,score\nAda,98\n", "text/csv")},
    )
    assert second.status_code == 200, second.text

    resp = client.post(
        f"/workers/{worker_id}/runs",
        headers=owner_b,
        json={"inputs": {"upload": second.json()["sha256"]}, "trigger_source": "manual"},
    )

    assert resp.status_code == 200, resp.text


def test_get_with_body_is_rejected(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.request("GET", "/workers", headers=_AUTH_HEADER, content=b"x")

    assert resp.status_code == 413, resp.text
    assert resp.json() == {"detail": "Request body not allowed"}


def test_new_worker_from_prompt_requires_auth(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post("/workers/new/from-prompt", json={"prompt": "draft a worker"})

    assert resp.status_code == 401, resp.text


def test_new_worker_from_prompt_oversized_body_rejected(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/workers/new/from-prompt",
        headers=_AUTH_HEADER,
        json={"prompt": "x" * (300 * 1024)},
    )

    assert resp.status_code == 413, resp.text
    assert resp.json() == {
        "detail": "Request body is too large. Reduce the payload size and try again."
    }


def test_run_creation_quota_is_shared_across_workers_and_ips(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, run_create_rate_minute=3)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_ids = [f"s13-run-quota-{idx}" for idx in range(3)]
    for worker_id in worker_ids:
        _insert_minimal_worker(main, worker_id)

    statuses = []
    bodies = []
    for idx in range(4):
        headers = {**_AUTH_HEADER, "x-forwarded-for": f"203.0.113.{idx + 1}"}
        resp = client.post(
            f"/workers/{worker_ids[idx % len(worker_ids)]}/runs",
            headers=headers,
            json={"inputs": {}, "trigger_source": "manual"},
        )
        statuses.append(resp.status_code)
        bodies.append(resp.text)

    assert statuses == [200, 200, 200, 429], bodies
    assert "Retry-After" in resp.headers
    assert resp.json() == {"detail": "Run creation rate limit exceeded: 3/60s"}


def test_run_creation_quota_defaults_to_safe_global_limit(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, run_create_rate_minute=None)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_ids = [f"s13-default-run-quota-{idx}" for idx in range(3)]
    for worker_id in worker_ids:
        _insert_minimal_worker(main, worker_id)

    statuses = []
    for idx in range(11):
        resp = client.post(
            f"/workers/{worker_ids[idx % len(worker_ids)]}/runs",
            headers={**_AUTH_HEADER, "x-forwarded-for": f"203.0.113.{idx + 1}"},
            json={"inputs": {}, "trigger_source": "manual"},
        )
        statuses.append(resp.status_code)

    assert statuses == [200] * 10 + [429], statuses
    assert resp.json() == {"detail": "Run creation rate limit exceeded: 10/60s"}
    assert "Retry-After" in resp.headers


def test_replay_route_shares_run_creation_quota(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, run_create_rate_minute=1)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_id = "s13-replay-quota-worker"
    _insert_minimal_worker(main, worker_id)

    first = client.post(
        f"/workers/{worker_id}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {}, "trigger_source": "manual"},
    )
    assert first.status_code == 200, first.text
    run_id = first.json()["run_id"]

    replay = client.post(f"/workers/{worker_id}/runs/{run_id}/replay", headers=_AUTH_HEADER)

    assert replay.status_code == 429, replay.text
    assert replay.json() == {"detail": "Run creation rate limit exceeded: 1/60s"}
    assert "Retry-After" in replay.headers


def test_run_creation_quota_applies_per_worker(monkeypatch, tmp_path):
    monkeypatch.setenv("WORKEROS_RUN_CREATE_PER_WORKER_RATE_LIMIT", "2")
    main = _load_api(monkeypatch, tmp_path, run_create_rate_minute=10)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_a = "s13-worker-a"
    worker_b = "s13-worker-b"
    _insert_minimal_worker(main, worker_a)
    _insert_minimal_worker(main, worker_b)

    first = client.post(
        f"/workers/{worker_a}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {}, "trigger_source": "manual"},
    )
    second = client.post(
        f"/workers/{worker_a}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {}, "trigger_source": "manual"},
    )
    third = client.post(
        f"/workers/{worker_a}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {}, "trigger_source": "manual"},
    )
    other_worker = client.post(
        f"/workers/{worker_b}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {}, "trigger_source": "manual"},
    )

    assert [first.status_code, second.status_code, third.status_code, other_worker.status_code] == [200, 200, 429, 200]
    assert third.json() == {"detail": "Run creation rate limit exceeded: 2/60s"}
    assert "Retry-After" in third.headers


def test_replay_quota_applies_per_run_id(monkeypatch, tmp_path):
    monkeypatch.setenv("WORKEROS_RUN_CREATE_PER_WORKER_RATE_LIMIT", "10")
    monkeypatch.setenv("WORKEROS_RUN_REPLAY_PER_RUN_RATE_LIMIT", "2")
    main = _load_api(monkeypatch, tmp_path, run_create_rate_minute=10)
    client = TestClient(main.app)
    monkeypatch.setattr(main, "start_run", lambda *args, **kwargs: None)
    worker_id = "s13-replay-per-run"
    _insert_minimal_worker(main, worker_id)

    created = client.post(
        f"/workers/{worker_id}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {}, "trigger_source": "manual"},
    )
    assert created.status_code == 200, created.text
    run_id = created.json()["run_id"]

    first = client.post(f"/workers/{worker_id}/runs/{run_id}/replay", headers=_AUTH_HEADER)
    second = client.post(f"/workers/{worker_id}/runs/{run_id}/replay", headers=_AUTH_HEADER)
    third = client.post(f"/workers/{worker_id}/runs/{run_id}/replay", headers=_AUTH_HEADER)

    assert [first.status_code, second.status_code, third.status_code] == [200, 200, 429]
    assert third.json() == {"detail": "Run creation rate limit exceeded: 2/60s"}
    assert "Retry-After" in third.headers


def test_sweep_connections_has_cooldown(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    first = client.post("/system/sweep-connections", headers=_AUTH_HEADER)
    second = client.post("/system/sweep-connections", headers=_AUTH_HEADER)

    assert first.status_code == 200, first.text
    assert first.json() == {"status": "sweep_started"}
    assert second.status_code == 429, second.text
    assert second.json() == {"detail": "Connection sweep already started recently"}
    assert "Retry-After" in second.headers


def test_system_metrics_and_overview_require_auth(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    metrics = client.get("/system/metrics")
    overview = client.get("/system/overview")

    assert metrics.status_code == 401, metrics.text
    assert overview.status_code == 401, overview.text


def test_sweep_connections_is_scoped_per_user(monkeypatch, tmp_path):
    monkeypatch.setenv("WORKEROS_ENABLE_USER_HEADER_SCOPE", "1")
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    seen_user_ids = []

    async def fake_sweep(*, user_id=None):
        seen_user_ids.append(user_id)

    import routers.connections as _conn
    monkeypatch.setattr(_conn, "_run_connection_sweep", fake_sweep)

    user_a = {**_AUTH_HEADER, "x-floom-user": "user-a"}
    user_b = {**_AUTH_HEADER, "x-floom-user": "user-b"}
    first = client.post("/system/sweep-connections", headers=user_a)
    second = client.post("/system/sweep-connections", headers=user_b)
    third = client.post("/system/sweep-connections", headers=user_a)
    time.sleep(0.05)

    assert first.status_code == 200, first.text
    assert second.status_code == 200, second.text
    assert third.status_code == 429, third.text
    assert seen_user_ids == ["user-a", "user-b"]


def test_context_routes_are_scoped_per_user(monkeypatch, tmp_path):
    monkeypatch.setenv("WORKEROS_ENABLE_USER_HEADER_SCOPE", "1")
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    user_a = {**_AUTH_HEADER, "x-floom-user": "user-a"}
    user_b = {**_AUTH_HEADER, "x-floom-user": "user-b"}
    context_name = "private-context"
    worker_yml = f"""
schema_version: "0.3"
name: "context-probe"
title: "Context Probe"
description: "Worker with a local context."
version: "0.1.0"
targets: ["generic"]
contexts:
  - "{context_name}"
exec:
  entry: "run.py"
  runtime: "python311"
  runner: "e2b"
  command: "python run.py"
  inputs: []
  outputs: []
trigger:
  type: "manual"
""".strip()

    created = client.post(f"/contexts/{context_name}", headers=user_a, json={"writeable": True})
    assert created.status_code == 200, created.text

    put_file = client.put(
        f"/contexts/{context_name}/files/notes.txt",
        headers=user_a,
        content=b"owner-only notes",
    )
    owner_list = client.get("/contexts", headers=user_a)
    foreign_list = client.get("/contexts", headers=user_b)
    foreign_get = client.get(f"/contexts/{context_name}", headers=user_b)
    foreign_file = client.get(f"/contexts/{context_name}/files/notes.txt", headers=user_b)
    foreign_put = client.put(
        f"/contexts/{context_name}/files/pwned.txt",
        headers=user_b,
        content=b"nope",
    )
    foreign_upload = client.post(
        f"/contexts/{context_name}/upload",
        headers=user_b,
        files={"files": ("upload.txt", b"nope", "text/plain")},
    )
    foreign_delete = client.delete(f"/contexts/{context_name}", headers=user_b)
    foreign_worker = client.post(
        "/workers",
        headers=user_b,
        json={"worker_yml": worker_yml, "run_py": "def run(inputs, context):\n    return {'ok': True}\n"},
    )

    assert put_file.status_code == 200, put_file.text
    assert [item["name"] for item in owner_list.json()] == [context_name]
    assert foreign_list.json() == []
    assert foreign_get.status_code == 404, foreign_get.text
    assert foreign_file.status_code == 404, foreign_file.text
    assert foreign_put.status_code == 404, foreign_put.text
    assert foreign_upload.status_code == 404, foreign_upload.text
    assert foreign_delete.status_code == 404, foreign_delete.text
    assert foreign_worker.status_code == 400, foreign_worker.text
    assert foreign_worker.json() == {"detail": f"Context not found: {context_name}"}


def test_scoped_users_can_reuse_the_same_context_name(monkeypatch, tmp_path):
    monkeypatch.setenv("WORKEROS_ENABLE_USER_HEADER_SCOPE", "1")
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    user_a = {**_AUTH_HEADER, "x-floom-user": "user-a"}
    user_b = {**_AUTH_HEADER, "x-floom-user": "user-b"}

    create_a = client.post("/contexts/shared-context", headers=user_a, json={"writeable": True})
    create_b = client.post("/contexts/shared-context", headers=user_b, json={"writeable": True})
    put_a = client.put(
        "/contexts/shared-context/files/notes.txt",
        headers=user_a,
        content=b"owner-a",
    )
    put_b = client.put(
        "/contexts/shared-context/files/notes.txt",
        headers=user_b,
        content=b"owner-b",
    )
    get_a = client.get("/contexts/shared-context/files/notes.txt", headers=user_a)
    get_b = client.get("/contexts/shared-context/files/notes.txt", headers=user_b)

    assert create_a.status_code == 200, create_a.text
    assert create_b.status_code == 200, create_b.text
    assert put_a.status_code == 200, put_a.text
    assert put_b.status_code == 200, put_b.text
    assert get_a.content == b"owner-a"
    assert get_b.content == b"owner-b"

    contexts_root = tmp_path / "contexts"
    assert not (contexts_root / "shared-context").exists()
    assert (contexts_root / "user-a" / "shared-context" / "notes.txt").read_bytes() == b"owner-a"
    assert (contexts_root / "user-b" / "shared-context" / "notes.txt").read_bytes() == b"owner-b"


def _setup_rate_limited_draft_client(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, draft_rate_hour=2)
    client = TestClient(main.app)
    payload = _valid_draft_payload(name="s13-rate-limited")
    monkeypatch.setattr(main, "_call_draft_llm", lambda *args, **kwargs: payload)
    return main, client


def test_draft_from_prompt_requires_auth(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post("/workers/draft-from-prompt", json={"prompt": "draft a worker"})

    assert resp.status_code == 401, resp.text


def test_from_bundle_requires_auth(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/workers/from-bundle",
        files={"bundle": ("bad.zip", b"not a zip", "application/zip")},
    )

    assert resp.status_code == 401, resp.text


def _consume_two_draft_slots(client: TestClient):
    first = client.post("/workers/draft-from-prompt", json={"prompt": "first"}, headers=_AUTH_HEADER)
    assert first.status_code == 200, first.text
    second = client.post("/workers/draft-and-create", json={"prompt": "second"}, headers=_AUTH_HEADER)
    assert second.status_code == 200, second.text


def test_draft_endpoints_share_hourly_cap(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    third = client.post("/workers/draft-from-prompt", json={"prompt": "third"}, headers=_AUTH_HEADER)
    assert third.status_code == 429, third.text
    assert third.json() == {"detail": "Draft rate limit reached: 2/hour. Try again later."}


def test_draft_file_path_shares_hourly_cap(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, draft_rate_hour=1)
    client = TestClient(main.app)

    first = client.post(
        "/workers/draft-and-create",
        json={"files": [{"path": "worker.yml", "content": _worker_yml("s13-file-draft-one")}]},
        headers=_AUTH_HEADER,
    )
    second = client.post(
        "/workers/draft-and-create",
        json={"files": [{"path": "worker.yml", "content": _worker_yml("s13-file-draft-two")}]},
        headers=_AUTH_HEADER,
    )

    assert first.status_code == 200, first.text
    assert second.status_code == 429, second.text
    assert second.json() == {"detail": "Draft rate limit reached: 1/hour. Try again later."}


def test_draft_limit_sets_retry_after_header(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    third = client.post("/workers/draft-from-prompt", json={"prompt": "third"}, headers=_AUTH_HEADER)
    assert third.status_code == 429, third.text
    assert "Retry-After" in third.headers
    retry_after = int(third.headers["Retry-After"])
    assert 1 <= retry_after <= 3600


def test_draft_from_prompt_treats_metadata_urls_as_plain_text(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    captured: dict[str, str] = {}
    network_attempts: list[tuple[Any, ...]] = []
    original_openai = sys.modules.get("openai")
    draft_payload = _valid_draft_payload(name="s13-plain-text-prompt")

    def fake_call_draft_llm(user_message, _extra=None):
        captured["user_message"] = user_message
        return draft_payload

    monkeypatch.setattr(main, "_call_draft_llm", fake_call_draft_llm)
    sys.modules["openai"] = types.SimpleNamespace(OpenAI=lambda api_key=None: object())

    import socket

    original_create_connection = socket.create_connection

    def fail_network(*args, **kwargs):
        network_attempts.append(args)
        raise AssertionError("unexpected network access during draft-from-prompt")

    socket.create_connection = fail_network
    try:
        resp = client.post(
            "/workers/draft-from-prompt",
            headers=_AUTH_HEADER,
            json={"prompt": "fetch http://169.254.169.254/latest/meta-data/iam/security-credentials/"},
        )
    finally:
        socket.create_connection = original_create_connection
        if original_openai is None:
            sys.modules.pop("openai", None)
        else:
            sys.modules["openai"] = original_openai

    assert resp.status_code == 200, resp.text
    assert "169.254.169.254" in captured["user_message"]
    assert network_attempts == []


def test_system_metrics_includes_drafts_last_hour(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    metrics = client.get("/system/metrics", headers=_AUTH_HEADER)
    assert metrics.status_code == 200, metrics.text
    assert "drafts_last_hour" in metrics.json()
    assert metrics.json()["drafts_last_hour"] == 2


def test_secret_test_blocks_platform_secret_enumeration(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    for name in [
        "OPENAI_API_KEY",
        "FLOOM_SECRET",
        "E2B_API_KEY",
        "COMPOSIO_API_KEY",
        "THIS_SECRET_DOES_NOT_EXIST_AUDIT",
    ]:
        resp = client.post(f"/secrets/{name}/test", headers=_AUTH_HEADER)
        assert resp.status_code == 404, resp.text
        body = resp.text
        assert "valid" not in body
        assert "chars" not in body
        assert "OpenAI" not in body
        assert "not set" not in body
        assert name not in body


def test_secret_test_for_user_secret_is_generic(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    save = client.post(
        "/secrets/USER_AUDIT_SECRET",
        headers=_AUTH_HEADER,
        json={"value": "super-secret-value"},
    )
    assert save.status_code == 200, save.text

    resp = client.post("/secrets/USER_AUDIT_SECRET/test", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    assert resp.json() == {"status": "valid", "reason": "Secret is configured."}
    assert "super-secret-value" not in resp.text
    assert "chars" not in resp.text
    assert "USER_AUDIT_SECRET" not in resp.text


def test_run_download_omits_sensitive_inputs_logs_and_transcript(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, _transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    resp = client.get(f"/runs/{run_id}/download", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    assert resp.headers.get("content-type", "").startswith("application/zip")

    zip_path = tmp_path / "s13-run-download.zip"
    zip_path.write_bytes(resp.content)
    with zipfile.ZipFile(zip_path, "r") as zf:
        names = set(zf.namelist())
        assert "metadata.json" in names
        assert "outputs.json" in names
        assert "README.txt" in names
        assert "artifacts/result.txt" in names
        assert "inputs.json" not in names
        assert "logs.txt" not in names
        assert "artifacts/transcript.jsonl" not in names
        assert "private user input" not in zf.read("outputs.json").decode("utf-8")


def test_run_detail_omits_sensitive_inputs_logs_trace_and_transcript(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    resp = client.get(f"/runs/{run_id}", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["input"] == {}
    assert body["output"] == {"summary": "public output"}
    assert body["transcript"] == []
    assert [artifact["name"] for artifact in body["artifacts"]] == ["result.txt"]
    assert "trace_id" not in resp.text
    assert "trace_a2278662e7ae4e05" not in resp.text
    assert "mode=agent" not in resp.text
    assert "runner=e2b" not in resp.text

    transcript_download = client.get(
        f"/runs/{run_id}/artifacts/{transcript_artifact_id}/download",
        headers=_AUTH_HEADER,
    )
    assert transcript_download.status_code == 404, transcript_download.text


def test_run_events_redact_trace_ids_and_internal_metadata(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    worker_id = f"s13-events-worker-{uuid.uuid4().hex[:8]}"
    run_id = f"run_{uuid.uuid4().hex}"
    _insert_minimal_worker(main, worker_id)
    now = main.now_iso()
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO runs
                (id, worker_id, status, trigger_source, runner, input_json, created_at)
            VALUES (?, ?, 'running', 'manual', 'skill', ?, ?)
            """,
            (run_id, worker_id, "{}", now),
        )

    run_service = importlib.import_module("run_service")

    def emit_events():
        run_service.add_log(
            run_id,
            "trace_a2278662e7ae4e05 mode=agent runner=e2b private log",
            trace_id="trace_a2278662e7ae4e05",
            user_id="local-user",
        )
        run_service.update_run_status(
            run_id,
            main.RunStatus.COMPLETED.value,
            error="thread_a2278662e7ae4e05 runner=e2b",
            user_id="local-user",
        )

    events = []

    def consume_events():
        with client.stream("GET", f"/runs/{run_id}/events", headers=_AUTH_HEADER) as response:
            assert response.status_code == 200, response.text
            for line in response.iter_lines():
                if not line.startswith("data:"):
                    continue
                event = json.loads(line[5:].strip())
                events.append(event)
                if event.get("status") in (main.RunStatus.COMPLETED.value, main.RunStatus.FAILED.value):
                    break

    consumer = threading.Thread(target=consume_events, daemon=True)
    consumer.start()
    deadline = time.time() + 5.0
    while time.time() < deadline:
        with main._sse_lock:
            if main._sse_queues.get(run_id):
                break
        time.sleep(0.05)
    with main._sse_lock:
        assert main._sse_queues.get(run_id), "SSE consumer did not register"
    emitter = threading.Thread(target=emit_events, daemon=True)
    emitter.start()
    emitter.join(timeout=1)
    consumer.join(timeout=2)
    assert not consumer.is_alive(), "SSE consumer did not finish"

    body = json.dumps(events)
    assert "trace_a2278662e7ae4e05" not in body
    assert "\"trace_id\"" not in body
    assert "mode=agent" not in body
    assert "runner=e2b" not in body
    assert "[redacted-id]" in body
    assert "[redacted-metadata]" in body


def test_cancel_completed_run_does_not_reveal_existence(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, _transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    existing = client.post(f"/runs/{run_id}/cancel", headers=_AUTH_HEADER)
    missing = client.post("/runs/run_missing_cancel_probe/cancel", headers=_AUTH_HEADER)

    assert existing.status_code == 404, existing.text
    assert missing.status_code == 404, missing.text
    assert existing.json() == missing.json() == {"detail": "Run not found"}
    assert "completed" not in existing.text
    assert run_id not in existing.text


def test_bundle_snapshot_missing_does_not_reveal_run_existence(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    run_id, _transcript_artifact_id = _insert_sensitive_run(main, tmp_path)

    existing = client.get(f"/runs/{run_id}/bundle/worker.yml", headers=_AUTH_HEADER)
    missing = client.get("/runs/run_missing_bundle_probe/bundle/worker.yml", headers=_AUTH_HEADER)

    assert existing.status_code == 404, existing.text
    assert missing.status_code == 404, missing.text
    assert existing.json() == missing.json() == {"detail": "Bundle file not found"}
    assert run_id not in existing.text


def test_file_input_rejects_foreign_upload_sha(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    worker_id = "s13-file-owner-worker"
    _insert_file_input_worker(main, worker_id)

    content = b"name,score\nAda,98\n"
    sha256 = hashlib.sha256(content).hexdigest()
    main.ensure_blob_dir(sha256).write_bytes(content)
    with main.get_db() as conn:
        conn.execute(
            """
            INSERT INTO files (id, filename, media_type, size_bytes, uploaded_by, uploaded_at, ref_count)
            VALUES (?, 'scores.csv', 'text/csv', ?, 'other-user', ?, 0)
            """,
            (sha256, len(content), main.now_iso()),
        )

    resp = client.post(
        f"/workers/{worker_id}/runs",
        headers=_AUTH_HEADER,
        json={"inputs": {"upload": sha256}, "trigger_source": "manual"},
    )

    assert resp.status_code == 403, resp.text
    assert resp.json() == {"detail": "Uploaded file not found: upload"}


def test_stock_worker_delete_is_blocked_even_when_source_missing(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    _insert_minimal_worker(main, "research_brief")

    resp = client.delete("/workers/research_brief", headers=_AUTH_HEADER)
    assert resp.status_code == 403, resp.text
    with main.get_db() as conn:
        row = conn.execute("SELECT id FROM workers WHERE id = 'research_brief'").fetchone()
    assert row is not None


def test_stock_worker_webhook_secret_rotate_is_blocked(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post("/workers/research_brief/webhook-secret/rotate", headers=_AUTH_HEADER)

    assert resp.status_code == 403, resp.text
    assert resp.json() == {"detail": "Stock workers cannot be modified through the API"}


def test_stock_worker_direct_mutations_block_but_create_can_fork(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    _insert_minimal_worker(main, "research_brief")
    worker_yml = _worker_yml("research_brief")

    create_resp = client.post(
        "/workers",
        headers=_AUTH_HEADER,
        json={"worker_yml": worker_yml, "run_py": "print('pwned')\n"},
    )
    put_resp = client.put(
        "/workers/research_brief",
        headers=_AUTH_HEADER,
        json={"worker_yml": worker_yml, "run_py": "print('pwned')\n"},
    )
    patch_resp = client.patch(
        "/workers/research_brief",
        headers=_AUTH_HEADER,
        json={"input_values": {"topic": "pwned"}},
    )
    files_resp = client.put(
        "/workers/research_brief/files",
        headers=_AUTH_HEADER,
        json={"files": [{"path": "worker.yml", "content": worker_yml}]},
    )

    assert create_resp.status_code == 200, create_resp.text
    assert create_resp.json()["id"] == "research-brief-copy"
    assert create_resp.json()["is_example"] is False
    assert put_resp.status_code == 403, put_resp.text
    assert put_resp.json() == {"detail": "Stock workers cannot be modified through the API"}
    assert patch_resp.status_code == 403, patch_resp.text
    assert files_resp.status_code == 403, files_resp.text
    assert files_resp.json() == {"detail": "Stock workers cannot be modified through the API"}


def test_worker_schema_validation_does_not_leak_pydantic_details(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.post(
        "/workers",
        headers=_AUTH_HEADER,
        json={"worker_yml": "name: bad\ndescription: bad\n", "run_py": "print('ok')\n"},
    )

    assert resp.status_code == 400, resp.text
    assert "errors.pydantic.dev" not in resp.text


def test_openapi_does_not_document_webhook_token_auth(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.get("/openapi.json", headers=_AUTH_HEADER)

    assert resp.status_code == 200, resp.text
    assert "?token=<webhook_token>" not in resp.text
    assert "X-Floom-Signature header" not in resp.text


def test_from_bundle_rejects_symlinks(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    name = "s13-symlink-worker"

    resp = client.post(
        "/workers/from-bundle",
        headers=_AUTH_HEADER,
        files={"bundle": ("symlink.zip", io.BytesIO(_symlink_bundle(name)), "application/zip")},
    )

    assert resp.status_code == 400, resp.text
    assert "symlink" in resp.text.lower()
    assert not (tmp_path / "workers" / name).exists()


def test_from_bundle_rejects_nested_traversal(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)
    name = "s13-nested-traversal-worker"

    resp = client.post(
        "/workers/from-bundle",
        headers=_AUTH_HEADER,
        files={"bundle": ("nested.zip", io.BytesIO(_nested_traversal_bundle(name)), "application/zip")},
    )

    assert resp.status_code == 400, resp.text
    assert "invalid path" in resp.text.lower()
    assert not (tmp_path / "workers" / name).exists()


def test_from_bundle_is_rate_limited(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    responses = [
        client.post(
            "/workers/from-bundle",
            headers=_AUTH_HEADER,
            files={"bundle": ("bad.zip", io.BytesIO(b"not a zip"), "application/zip")},
        )
        for _ in range(11)
    ]

    assert [resp.status_code for resp in responses[:10]] == [400] * 10
    assert responses[10].status_code == 429


def test_webhook_aliases_match_original_routes(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    bad_sig_headers = {
        "webhook-id": "msg_bad",
        "webhook-timestamp": str(int(time.time())),
        "webhook-signature": "v1,bad",
        "Content-Type": "application/json",
    }
    body = json.dumps({"metadata": {"trigger_id": "ct_missing"}}).encode()

    original = client.post("/composio-events", content=body, headers=bad_sig_headers)
    alias = client.post("/webhooks/composio-events", content=body, headers=bad_sig_headers)
    assert original.status_code == 401, original.text
    assert alias.status_code == 401, alias.text
    assert original.json() == alias.json()

    # Valid signatures should behave the same too (404 in both paths with no worker match).
    sig_headers = _signed_headers(body, "whsec-test")
    original_valid = client.post("/composio-events", content=body, headers=sig_headers)
    alias_valid = client.post("/webhooks/composio-events", content=body, headers=sig_headers)
    assert original_valid.status_code == 404, original_valid.text
    assert alias_valid.status_code == 404, alias_valid.text
    assert original_valid.json() == alias_valid.json()

    callback_qs = "?connection_id=unknown_conn&status=success"
    cb_original = client.get(f"/connections/callback{callback_qs}", follow_redirects=False)
    cb_alias = client.get(f"/webhooks/oauth-callback{callback_qs}", follow_redirects=False)
    assert cb_original.status_code == cb_alias.status_code
    assert cb_original.headers.get("location") == cb_alias.headers.get("location")


def test_chat_per_user_quota_returns_429(monkeypatch, tmp_path):
    """/chat calls OpenAI per request; a per-user quota must cap the bill-burn path."""
    main = _load_api(monkeypatch, tmp_path)
    monkeypatch.setenv("WORKEROS_CHAT_RATE_LIMIT", "2")
    monkeypatch.setenv("WORKEROS_CHAT_RATE_WINDOW_SECONDS", "60")
    monkeypatch.setenv("WORKEROS_CHAT_COST_UNITS_LIMIT", "0")

    # Stub stream_chat so the test never reaches OpenAI: just emit a finish part.
    import chat_service

    async def _fake_stream_chat(*, message, user_id, conversation_id, part_queue, source="web"):
        await part_queue.put({"type": "finish", "conversation_id": "c1", "message_id": "m1"})

    monkeypatch.setattr(chat_service, "stream_chat", _fake_stream_chat)

    client = TestClient(main.app)

    # First two requests are within quota.
    for _ in range(2):
        resp = client.post("/chat", headers=_AUTH_HEADER, json={"message": "hi"})
        assert resp.status_code == 200, resp.text

    # Third request in the same window is rejected with 429 + Retry-After.
    blocked = client.post("/chat", headers=_AUTH_HEADER, json={"message": "hi"})
    assert blocked.status_code == 429, blocked.text
    assert "Retry-After" in blocked.headers
    assert "Chat rate limit exceeded" in blocked.json()["detail"]


def test_chat_cost_quota_exhaustion_returns_retry_after(monkeypatch, tmp_path):
    _load_api(monkeypatch, tmp_path)
    monkeypatch.setenv("WORKEROS_CHAT_RATE_LIMIT", "0")
    monkeypatch.setenv("WORKEROS_CHAT_COST_UNITS_LIMIT", "3")
    monkeypatch.setenv("WORKEROS_CHAT_COST_WINDOW_SECONDS", "60")
    monkeypatch.setenv("WORKEROS_CHAT_MODEL", "bedrock/us.anthropic.claude-sonnet-4-6")

    from auth import AuthContext
    from services.quota import _enforce_chat_quota
    from fastapi import HTTPException

    # Sonnet multiplier makes a short message cost 2 units: first allowed,
    # second would exceed the 3-unit bucket.
    _enforce_chat_quota(AuthContext(user_id="alice"), message="hi")
    try:
        _enforce_chat_quota(AuthContext(user_id="alice"), message="hi")
    except HTTPException as exc:
        assert exc.status_code == 429
        assert "Retry-After" in exc.headers
        assert "cost quota" in str(exc.detail)
    else:
        raise AssertionError("second cost-bearing chat should be quota limited")


def test_chat_cost_quota_is_scoped_by_identity_and_workspace(monkeypatch, tmp_path):
    _load_api(monkeypatch, tmp_path)
    monkeypatch.setenv("WORKEROS_CHAT_RATE_LIMIT", "0")
    monkeypatch.setenv("WORKEROS_CHAT_COST_UNITS_LIMIT", "1")
    monkeypatch.setenv("WORKEROS_CHAT_COST_WINDOW_SECONDS", "60")
    monkeypatch.setenv("WORKEROS_CHAT_MODEL", "gpt-4.1-mini")

    from auth import AuthContext
    from services.quota import _enforce_chat_quota
    from fastapi import HTTPException

    _enforce_chat_quota(AuthContext(user_id="alice"), message="hi")
    _enforce_chat_quota(AuthContext(user_id="bob"), message="hi")
    _enforce_chat_quota(AuthContext(user_id="alice__ws_1234567890abcd"), message="hi")

    try:
        _enforce_chat_quota(AuthContext(user_id="alice"), message="again")
    except HTTPException as exc:
        assert exc.status_code == 429
    else:
        raise AssertionError("same identity/workspace bucket should be exhausted")
