"""PR S13 tests: info-disclosure cleanup, draft caps, and webhook aliases."""

from __future__ import annotations

import hashlib
import hmac
import importlib
import json
import os
import base64
import sys
import time
import types
from typing import Any, Dict

from fastapi.testclient import TestClient


API_DIR = os.path.join(os.path.dirname(__file__), "..", "apps", "api")
if API_DIR not in sys.path:
    sys.path.insert(0, API_DIR)


_AUTH_HEADER = {"x-floom-secret": "test-secret-s13"}


def _load_api(monkeypatch, tmp_path, *, draft_rate_hour: int = 20):
    workers_dir = tmp_path / "workers"
    workers_dir.mkdir()
    db_path = tmp_path / "floom.db"

    monkeypatch.setenv("FLOOM_DB", str(db_path))
    monkeypatch.setenv("FLOOM_WORKERS_DIR", str(workers_dir))
    monkeypatch.setenv("FLOOM_SECRET", _AUTH_HEADER["x-floom-secret"])
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
    monkeypatch.setenv("E2B_API_KEY", "e2b-test")
    monkeypatch.setenv("COMPOSIO_API_KEY", "cmp-test")
    monkeypatch.setenv("COMPOSIO_WEBHOOK_SIGNING_KEY", "whsec-test")
    monkeypatch.setenv("WORKERS_FRONTEND_URL", "https://workers.floom.dev")
    monkeypatch.setenv("WORKEROS_DRAFT_RATE_HOUR", str(draft_rate_hour))

    for name in [
        "main",
        "db",
        "models",
        "worker_registry",
        "run_service",
        "composio_client",
        "scheduler",
    ]:
        sys.modules.pop(name, None)

    # Avoid startup scheduler side-effects in tests.
    sys.modules["scheduler"] = types.SimpleNamespace(
        start_scheduler=lambda: None,
        stop_scheduler=lambda: None,
    )
    return importlib.import_module("main")


def _valid_draft_payload(name: str = "s13-draft-worker") -> Dict[str, Any]:
    worker_yml = f"""
schema_version: "0.3"
name: "{name}"
title: "S13 Draft Worker"
description: "Worker generated by tests."
version: "0.1.0"
targets: ["generic"]
exec:
  entry: "SKILL.md"
  runtime: "skill"
  runner: "e2b"
trigger:
  type: "manual"
"""
    return {
        "worker_yml": worker_yml.strip(),
        "skill_md": "You are a test worker.",
        "suggested_name": name,
        "suggested_title": "S13 Draft Worker",
        "requirements": [],
        "required_connections": [],
        "required_secrets": [],
        "inputs": [{"name": "topic", "type": "string", "label": "Topic", "required": True}],
        "outputs": [{"name": "summary", "type": "markdown", "label": "Summary"}],
        "files": [
            {"path": "worker.yml", "content": worker_yml.strip()},
            {"path": "SKILL.md", "content": "You are a test worker."},
        ],
    }


def _signed_headers(body: bytes, signing_key: str) -> Dict[str, str]:
    msg_id = "msg_s13"
    ts = str(int(time.time()))
    payload = f"{msg_id}.{ts}.{body.decode('utf-8')}".encode()
    digest = hmac.new(signing_key.encode(), payload, hashlib.sha256).digest()
    sig = "v1," + base64.b64encode(digest).decode()
    return {
        "webhook-id": msg_id,
        "webhook-timestamp": ts,
        "webhook-signature": sig,
        "Content-Type": "application/json",
    }


def test_system_info_is_redacted(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    resp = client.get("/system/info", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert set(body.keys()) == {"version", "started_at", "python_version", "runner"}
    assert body["runner"] == "e2b"
    assert "workers_dir" not in body
    assert "db_path" not in body
    assert "artifacts_dir" not in body


def test_platform_config_is_redacted(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    # Simulate one missing required var and one set required var.
    monkeypatch.setenv("OPENAI_API_KEY", "sk-test")
    monkeypatch.delenv("COMPOSIO_API_KEY", raising=False)

    resp = client.get("/system/platform-config", headers=_AUTH_HEADER)
    assert resp.status_code == 200, resp.text
    body = resp.json()

    assert set(body.keys()) == {"all_required_set", "missing", "set_count", "required_count"}
    assert "OPENAI_API_KEY" not in body["missing"]  # set names must not be enumerated
    assert "COMPOSIO_API_KEY" in body["missing"]
    assert body["set_count"] < body["required_count"]


def _setup_rate_limited_draft_client(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path, draft_rate_hour=2)
    client = TestClient(main.app)
    payload = _valid_draft_payload(name="s13-rate-limited")
    monkeypatch.setattr(main, "_call_draft_llm", lambda *args, **kwargs: payload)
    return main, client


def _consume_two_draft_slots(client: TestClient):
    first = client.post("/workers/draft-from-prompt", json={"prompt": "first"}, headers=_AUTH_HEADER)
    assert first.status_code == 200, first.text
    second = client.post("/workers/draft-and-create", json={"prompt": "second"}, headers=_AUTH_HEADER)
    assert second.status_code == 200, second.text


def test_draft_endpoints_share_hourly_cap(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    third = client.post("/workers/draft-from-prompt", json={"prompt": "third"}, headers=_AUTH_HEADER)
    assert third.status_code == 429, third.text
    assert third.json() == {"detail": "Draft rate limit reached: 2/hour. Try again later."}


def test_draft_limit_sets_retry_after_header(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    third = client.post("/workers/draft-from-prompt", json={"prompt": "third"}, headers=_AUTH_HEADER)
    assert third.status_code == 429, third.text
    assert "Retry-After" in third.headers
    retry_after = int(third.headers["Retry-After"])
    assert 1 <= retry_after <= 3600


def test_system_metrics_includes_drafts_last_hour(monkeypatch, tmp_path):
    _main, client = _setup_rate_limited_draft_client(monkeypatch, tmp_path)
    _consume_two_draft_slots(client)

    metrics = client.get("/system/metrics", headers=_AUTH_HEADER)
    assert metrics.status_code == 200, metrics.text
    assert "drafts_last_hour" in metrics.json()
    assert metrics.json()["drafts_last_hour"] == 2


def test_webhook_aliases_match_original_routes(monkeypatch, tmp_path):
    main = _load_api(monkeypatch, tmp_path)
    client = TestClient(main.app)

    bad_sig_headers = {
        "webhook-id": "msg_bad",
        "webhook-timestamp": str(int(time.time())),
        "webhook-signature": "v1,bad",
        "Content-Type": "application/json",
    }
    body = json.dumps({"metadata": {"trigger_id": "ct_missing"}}).encode()

    original = client.post("/composio-events", content=body, headers=bad_sig_headers)
    alias = client.post("/webhooks/composio-events", content=body, headers=bad_sig_headers)
    assert original.status_code == 401, original.text
    assert alias.status_code == 401, alias.text
    assert original.json() == alias.json()

    # Valid signatures should behave the same too (404 in both paths with no worker match).
    sig_headers = _signed_headers(body, "whsec-test")
    original_valid = client.post("/composio-events", content=body, headers=sig_headers)
    alias_valid = client.post("/webhooks/composio-events", content=body, headers=sig_headers)
    assert original_valid.status_code == 404, original_valid.text
    assert alias_valid.status_code == 404, alias_valid.text
    assert original_valid.json() == alias_valid.json()

    callback_qs = "?connection_id=unknown_conn&status=success"
    cb_original = client.get(f"/connections/callback{callback_qs}", follow_redirects=False)
    cb_alias = client.get(f"/webhooks/oauth-callback{callback_qs}", follow_redirects=False)
    assert cb_original.status_code == cb_alias.status_code
    assert cb_original.headers.get("location") == cb_alias.headers.get("location")
